# YAML

neuro:
    api:
        logger:
            level: INFO
            handler_type: file
            path: /var/log/acme/neuro-api/
            filename: acme-neuro-api.log

    scripts:
        logger:
            level: INFO
