# YAML

twitter:
    consumer_key: ''
    consumer_secret: ''
    access_token: ''
    access_token_secret: ''


neuro:
    api:
        logger:
            level: INFO
            handler_type: file
            path: /var/log/acme/neuro-api/
            filename: acme-neuro-api.log

    scripts:
        logger:
            level: INFO
